version: '3.9'

services:
  little-link:
    image: ghcr.io/techno-tim/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=Techno Tim
      - META_DESCRIPTION=Techno Tim Link page
      - META_AUTHOR=Techno Tim
      - THEME=Dark
      - FAVICON_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
      - AVATAR_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
      - AVATAR_2X_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
      - AVATAR_ALT=Techno Tim Profile Pic
      - NAME=TechnoTim
      - BIO=Hey! Just a place where you can connect with me!
      - GITHUB=https://l.technotim.live/github
      - TWITTER=https://l.technotim.live/twitter
      - INSTAGRAM=https://l.technotim.live/instagram
      - YOUTUBE=https://l.technotim.live/subscribe
      - TWITCH=https://l.technotim.live/twitch/
      - DISCORD=https://l.technotim.live/discord
      - TIKTOK=https://l.technotim.live/tiktok
      - KIT=https://l.technotim.live/gear
      # - FACEBOOK=https://facebook.com
      # - FACEBOOK_MESSENGER=https://facebook.com
      # - LINKED_IN=https://linkedin.com
      # - PRODUCT_HUNT=https://www.producthunt.com/
      # - SNAPCHAT=https://www.snapchat.com/
      # - SPOTIFY=https://www.spotify.com/
      # - REDDIT=https://www.reddit.com/
      # - MEDIUM=https://medium.com
      # - PINTEREST=https://www.pinterest.com/
      # - EMAIL=you@example.com
      # - EMAIL_ALT=you@example.com
      # - SOUND_CLOUD=https://souncloud.com
      # - FIGMA=https://figma.com
      # - TELEGRAM=https://telegram.org/
      # - TUMBLR=https://www.tumblr.com/
      # - STEAM=https://steamcommunity.com/
      # - VIMEO=https://vimeo.com/
      # - WORDPRESS=https://wordpress.com/
      # - GOODREADS=https://www.goodreads.com/
      # - SKOOB=https://www.skoob.com.br/
      - FOOTER=Thanks for stopping by!
    ports:
      - 8080:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true